### ISSUE TITLE
Sub module result is not assigned to fpu_result

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#11]
Sub module result is not assigned to fpu_result because logic analyzer write enable is not present in condition  assaignment.
![image](https://user-images.githubusercontent.com/73219089/121145316-42e65280-c858-11eb-8ee5-4127875db77b.png)

**Comment by aghaalizeb-lm** [comment]
The logic has been updated, rerun your tests.

**Comment by hamzakhan1-lm** [comment]
This issue has been resolved.
