### ISSUE TITLE
Read from Result CSR is not assigned to rddata

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#12]
Read from Result CSR is not assigned to rddata instead la data is assigned.
assign rddata                  =  wb_valid_f ? 32'b0 : la_write_en ? (la_write & la_data) : int_rddata;

**Comment by aghaalizeb-lm** [comment]
The logic has been updated rerun your tests.

**Comment by hamzakhan1-lm** [comment]
The issue is resolved now and result csr value is correctly read by logic analyzer output.
