### ISSUE TITLE
GPIO issue : high impedence on mprj_io which is connected to fpu output

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#13]
When gpio is configured as a output from user project area the correct fpu result is not reaching to gpio output signal mprj_io. Below waveform shows the series of signals from fpu output to gpio signal mprj_io. Fpu output is correct (which is 0x00000003) but in module sky130_ef_io_gpio_pad_wraper input is correct but output is z.

![image](https://user-images.githubusercontent.com/73219089/121519471-2fc7b400-ca0b-11eb-93e0-8161edbd866e.png)

**Comment by komaljaved-lm** [comment]
Design has been updated
