### ISSUE TITLE
wishbone acknowledge is not set on every read/write to user_project_area(FPU)

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#2]
When we write first operand to user project area the wishbone acknowledge signal does not give high as a result read/write transfer is not completed through wishbone and next transfer does not start. Its not following the wishbone protocol instead acknowledge is set only when fpu results are valid.

**Comment by aghaalizeb-lm** [comment]
The acknowledge logic has been updated kindly run your tests again.

**Comment by hamzakhan1-lm** [comment]
ack signal is not in the  io port list of fpu_top but connected in instance. inter_gen is not in io port but present in instantiation.

**Comment by aghaalizeb-lm** [comment]
It has been updated kindly check again.

**Comment by hamzakhan1-lm** [comment]
Its working in case of write but in case of read ack is not set.

**Comment by aghaalizeb-lm** [comment]
Kindly check the logic again.

**Comment by hamzakhan1-lm** [comment]
wishbone read write acknowledge is working fine now.
