### ISSUE TITLE
wb_valid and valid_in is not set on same clock cycle [user project example]

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#3]
![image](https://user-images.githubusercontent.com/73219089/119803882-4b09ce00-bef9-11eb-9165-10815afcbd60.png)

According to above code valid_in should give value when wb_valid is high but according to the design valid_in gets flopped and delayed by 1 clock cycle while wb_valid is not flopped. As a result out reads the value of previously set valid_in.

![image](https://user-images.githubusercontent.com/73219089/119803622-0ed66d80-bef9-11eb-8cb9-dd22cc6e8dfc.png)

**Comment by aghaalizeb-lm** [comment]
I have updated the logic kindly check again

**Comment by hamzakhan1-lm** [comment]
wb_valid and valid_in are now set on same clock cycle.
