### ISSUE TITLE
Result csr changes its true value before reading 

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#4]
![image](https://user-images.githubusercontent.com/73219089/119812430-945e1b80-bf01-11eb-81cf-1d4e40eee323.png)

result changes its value on next clock cycle. As a result the csr which hold result value also chages and when read gives wrong value.

**Comment by aghaalizeb-lm** [comment]
The logic has been updated kindly check again.

**Comment by hamzakhan1-lm** [comment]
CSR resding correct value now.
