### ISSUE TITLE
fflags not reading correct excepton, issue with fflags enable

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#5]
![image](https://user-images.githubusercontent.com/73219089/120293017-49b41900-c2de-11eb-950a-ae85d6eebcaf.png)

After Operation is defined output is stored in result csr while exception is not stored in fflags csr because its enable wr_fflags_r is not set. Exception is valid only for same 1 clock cycle as the output. So you have to write to csr fflags at the same time as output.

**Comment by aghaalizeb-lm** [comment]
I have fixed this issue kindly rerun your test.

**Comment by hamzakhan1-lm** [comment]
working fine now. Thank you.
