### ISSUE TITLE
Valid_in gets to zero before div_valid_out set.

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#7]
Valid_in gets to zero befor div_valid_out set. As a result out variable in fpu_top did not read the correct value. In fact valid_in gets to 0 before divider even gives output.
![image](https://user-images.githubusercontent.com/73219089/120467470-a6d0cd00-c3b9-11eb-9bdb-fc183a8374b4.png)

valid_in[9] should be set at the time of div_valid_out =1 to read correct output value.

**Comment by aghaalizeb-lm** [comment]
The issue has been resolved check again.

**Comment by hamzakhan1-lm** [comment]
Working correct now. Thank you.
