### ISSUE TITLE
op_in is not assigned to op_out in case of f2i and i2f operation

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#8]
op_in is not assigned to op_out in case of f2i and i2f operation in fpu top. This op_in corresponds to signed or unsigned conversion in case of f2i and i2f modules.

![image](https://user-images.githubusercontent.com/73219089/120599069-7c861a80-c460-11eb-9dcd-7dcb356bfd1e.png)

Addinf valid_in[4] and valid_in[5] to the op_out assignment will fix the issue.

**Comment by aghaalizeb-lm** [comment]
Issue has been fixed rerun your test.

**Comment by hamzakhan1-lm** [comment]
This is working fine. However incase of i2f exception signal of ftoi_exception is assigned instead of itof_exception in fpu_top. Refer to figure above.

**Comment by aghaalizeb-lm** [comment]
It has also been fixed kindly rerun your tests.

**Comment by hamzakhan1-lm** [comment]
Test passing now. Thank you.
