### ISSUE TITLE
la_data is not connected to write bus of csr

### ISSUE THREAD

**Issue by hamzakhan1-lm** [Lampro-Mellon/Caravel_FPU#9]
la_data is not connected to write bus of csr as a result the input through logic analyser is not passed to csr and as a result inputs are not passed to fpu.

**Comment by aghaalizeb-lm** [comment]
The design has been updated kindly rerun your tests.

**Comment by hamzakhan1-lm** [comment]
line 95 of user project example has syntax error (missing ;)

**Comment by hamzakhan1-lm** [comment]
the data signal is not defined in user project example. It should be a 32 bit bus.

**Comment by aghaalizeb-lm** [comment]
It has been declared.

**Comment by hamzakhan1-lm** [comment]
issue has been resolved
